[project]
name = "hypixeltwitchbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "twitchio==2.10.0",
    "aiohttp",
    "python-dotenv",
]
